version: "3.4"

services:

  proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./certs/wildcard.127.0.0.1.xip.io:/etc/nginx/certs:ro
      - ./ca:/etc/nginx/ca:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro